apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - reconcile_job.yaml

configMapGenerator:
- name: reconcile-config
  files:
  - reconcile_apps.py

generatorOptions:
  disableNameSuffixHash: true
commonAnnotations:
#    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
