apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 3scale-tenant-dev

resources:
  - ../../base
  #backends
  - backends/svc-bms-backend.yaml
  - backends/svc-pmx-backend.yaml

  #products
  #- products/countries-openid-secret.yaml
  - products/echo-userkey.yaml
  #accounts
  - accounts/developeraccount-testak.yaml

  #account-users
  # - accounts/developeruser-testak.yaml
  #- accounts/secret-developeruser-testak.yaml

  # - applications/application-sample-openid.yaml
  # - applications/applicationauth.yaml
  # - applications/secret.yaml
  #- applications/reconcile_job.yaml
  #- applications/reconcile-apps.yaml
  - applications/application.yaml
  - applications/applicationauth.yaml
  - applications/applicationauthsecret.yaml


  #routes
  - routes/echo-userkey.yaml
  - routes/echo-userkey-staging.yaml

commonAnnotations:
    argocd.argoproj.io/sync-wave: "2"

patchesStrategicMerge:
  - patch-tenant-url-check-hook.yaml