apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: echo-userkey
  namespace: 3scale-tenant-dev
spec:
  path: /dev
  to:
    name: apicast-production
    weight: 100
    kind: Service
  host: api.apps.cluster-25gxt.dynamic.redhatworkshops.io
  tls: {}

