apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: 3scale-realm
spec:
  keycloakCRName: keycloak
  realm:
    realm: 3scale-realm
    enabled: true
    clients:
      - clientId: 3scale-client
        protocol: openid-connect
        secret: my-3scale-secret
        publicClient: false
        redirectUris:
          - "https://*.apps.cluster-25gxt.dynamic.redhatworkshops.io/auth/3scale/callback"
        standardFlowEnabled: true
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: true
    users:
    - username: service-account-3scale-client
      emailVerified: false
      enabled: true
      totp: false
      serviceAccountClientId: 3scale-client
      disableableCredentialTypes: []
      requiredActions: []
      realmRoles:
      - default-roles-3scale-realm
      clientRoles:
        realm-management:
        - view-users
        - manage-clients
        - create-client
      notBefore: 0
      groups: []
    
  
    # roles:
    #   client:
    #     realm-management:
    #       - name: manage-users
    # serviceAccountRealmRoles:
    #   - clientId: 3scale-client
    #     roles:
    #       - name: manage-users
    #         clientId: realm-management