apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak

resources:
  - ../../base
  - importrealm.yaml
#   - secret-realm.yaml
# patchesStrategicMerge:
#   - patch-job-create-realm.yaml
