apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

configMapGenerator:
- name: reconcile-config
  files:
  - reconcile_apps.py

generatorOptions:
  disableNameSuffixHash: true