apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - tenant-url-check-hook.yaml

configMapGenerator:
- name: reconcile-config
  files:
  - reconcile_apps.py

generatorOptions:
  disableNameSuffixHash: true