apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: svc-countries
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"

spec:
  name: "svc countries"
  systemName: svc_countries_backend
  description: "Backend del servicio svc_countries"
  privateBaseURL: "http://svc-countries.svc-countries.svc.cluster.local"
  providerAccountRef:
    name: dev-tenant-secret

  methods:
    get_countries_v1:
      friendlyName: "GET countries V1"
      description: ""
 

  mappingRules:
    - httpMethod: GET
      pattern: "/countries"
      metricMethodRef: get_countries_v1
      increment: 1
      last: true
