apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: 3scale-realm
spec:
  keycloakCRName: keycloak
  realm:
    realm: 3scale-realm
    enabled: true
    clients:
      - clientId: 3scale-client
        protocol: openid-connect
        secret: my-3scale-secret
        publicClient: false
        redirectUris:
          - "https://*.cluster-5pfhb.dynamic.redhatworkshops.io/auth/3scale/callback"
        standardFlowEnabled: true
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: true
    roles:
      client:
        - clientId: realm-management
          roles:
            - name: manage-users
    serviceAccountRealmRoles:
      - clientId: 3scale-client
        roles:
          - name: manage-users
            clientId: realm-management