apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperAccount
metadata:
  name: developeraccount-devsecops-dev
spec:
  orgName: testorg
  providerAccountRef:
    name: dev-tenant-secret
---
kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: developeruser-admin-dev
spec:
  username: admin-dev
  passwordCredentialsRef:
    name: developeruser-admin-dev-secret
  email: admin-dev@redhat.com
  role: admin
  developerAccountRef:
    name: developeraccount-devsecops-dev
  providerAccountRef:
    name: dev-tenant-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: developeruser-admin-dev-secret
stringData:
  password: "redhat"
