apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-url-check-hook-binding
subjects:
  - kind: ServiceAccount
    name: tenant-url-check-hook-sa
    namespace: ""
roleRef:
  kind: Role
  name: tenant-url-check-hook-role
  apiGroup: rbac.authorization.k8s.io
