apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 3scale-tenant-dev

resources:
  - ../../base
  #backends
  - backends/svc-countries.yaml
  #products
  - products/countries-openid-secret.yaml
  - products/countries-openid.yaml
  #accounts
  - accounts/developeraccount-devsecops.yaml

  #account-users
  - accounts/developeruser-admin.yaml
  - accounts/developeruser-admin-secret.yaml

  # - applications
  - applications/reconcile-apps.yaml

  # hook 3scale applications
  - ../../../../../components/hooks/reconcile-application-hook


commonAnnotations:
    argocd.argoproj.io/sync-wave: "2"

patchesStrategicMerge:
  - patch-tenant-url-check-hook.yaml
  - patch-reconcile-job.yaml