apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 3scale-tenant-dev

resources:
  - ../../base
  - backends/svc-countries.yaml
commonAnnotations:
    argocd.argoproj.io/sync-wave: "6"