apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 3scale-tenant-dev

resources:
  - ../../base
  #backends
  - backends/svc-countries.yaml
  #products
  - products/countries-openid-secret.yaml
  - products/countries-openid.yaml
commonAnnotations:
    argocd.argoproj.io/sync-wave: "6"