apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: svc-pmx-backend
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

spec:
  name: "svc pmx v1"
  systemName: svc_pmx_backend
  description: "Backend del servicio svc_bms_backend"
  privateBaseURL: "https://echo-api.3scale.net:443/dev/pmx/v1"
  providerAccountRef:
    name: dev-tenant-secret

  # methods:
  #   get_bms_v1:
  #     friendlyName: "GET countries V1"
  #     description: ""
 

  # mappingRules:
  #   - httpMethod: GET
  #     pattern: "/dev/bms/v1"
  #     metricMethodRef: get_bms_v1
  #     increment: 1
  #     last: true
